# This *experimental* workflow will try to build a PyInstaller binary
# using a Docker container.

name: Python - Run PyInstaller - Docker experimental

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  PRODUCT_NAME: Fansly Downloader NG

jobs:

  build-linux-generic:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Run PyInstaller via Docker
      uses: docker://fydeinc/pyinstaller
      env:
        SRCDIR: /github/workspace
        PLATFORMS: linux,alpine
      with:
        args: --name fansly-downloader-ng --console -i "${{ env.SRCDIR }}/resources/fansly_ng.ico" "${{ env.SRCDIR }}/fansly_downloader_ng.py"

    - name: Show dist contents
      run: ls -lhR
      working-directory: dist

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: ${{ env.PRODUCT_NAME }}
    #     path: |
    #       dist/${{ env.ARCHIVE_NAME }}
